const environment = import.meta.env;

export const variables = () => ({
  AUTH0_DOMAIN: environment.VITE_AUTH0_DOMAIN,
  AUTH0_CLIENTID: environment.VITE_AUTH0_CLIENTID,
  AUTH0_AUDIENCE: environment.VITE_AUTH0_AUDIENCE,
  ENVIRONMENT: "dev",
  SUBCRIPTION_SERVICE: environment.VITE_SUBCRIPTION_SERVICE,
  BUSINESS_API: environment.VITE_BUSINESS_API_BASE_URL,
  CREDIT_MODEL: environment.VITE_CREDIT_MODEL_URL,
  POS_API: environment.VITE_POS_API,
  APPOINTMENT_API_BASEURL: environment.VITE_BUSINESS_API_BASE_URL,
  DASHBOARD_API: environment.VITE_DASHBOARD_API,
});
